### ISSUE TITLE
How do I run the npm command?

### ISSUE THREAD

**Issue by umarmf343** [yungifez/skuul#282]
I keep getting this error when I run npm run build or npm run dev

and the website displays:

**Vite manifest not found at: /home/thebhcqm/portal2.thebadracademy.com.ng/public/build/manifest.json**

![image](https://user-images.githubusercontent.com/124717827/223782179-556ea158-7d6f-4111-8b50-8b0a622ca80b.png)

Im no too techy on this, I will appreciate step by step guidline, Thank you!

**Comment by yungifez** [comment]
Unfortunately, you can not run npm run build because you do not have npm installed

How to combat

- Clone this project locally 
- run npm run build 
- copy the manifest.json file and the build folder to the production server using FTP 

The only downside is, you'd have to do this after every update

**Comment by yungifez** [comment]
Honestly, I advise you not to use cpanel. Oracle has an always-free tier their vps

Or you can simply get a vps at very low costs

**Comment by yungifez** [comment]
Can I close this, or are you still having issues?

**Comment by umarmf343** [comment]
Yes you can close it, I think I need the VPS hosting instead of c-panel.
Thank you
